# Generated by Django 4.1.5 on 2023-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userdetailsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='samapp/static')),
                ('image', models.FileField(upload_to='samapp/static')),
                ('educationalqualification', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vaccancyuploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('jobtitle', models.CharField(max_length=35)),
                ('jobtype', models.CharField(choices=[('Part time', 'Part time'), ('Full time', 'Full time')], max_length=50)),
                ('worktype', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=30)),
                ('experiencerequired', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20)),
                ('qualificationrequired', models.CharField(max_length=100)),
            ],
        ),
    ]
