# Generated by Django 4.1.5 on 2023-01-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
