# Generated by Django 4.1.5 on 2023-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0002_alter_userdetailsmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapplyform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='samapp/static')),
            ],
        ),
    ]
