# Generated by Django 4.1.5 on 2023-01-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0003_jobapplyform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobapplyform',
            new_name='jobapplymodel',
        ),
    ]
