# Generated by Django 4.1.5 on 2023-01-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0004_rename_jobapplyform_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='email2',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
