# Generated by Django 4.1.5 on 2023-01-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0008_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='cid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
