# Generated by Django 4.1.5 on 2023-01-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0010_viewappliedusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewappliedusers',
        ),
    ]
