# Generated by Django 3.2.9 on 2023-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0011_delete_viewappliedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('course', models.CharField(choices=[('kerala', 'kerala'), ('tamil nadu', 'tamil nadu'), ('karnataka', 'karnataka')], max_length=30)),
                ('english', models.BooleanField(default=False)),
                ('malayalam', models.BooleanField(default=False)),
            ],
        ),
    ]
